### ISSUE TITLE
Possible to highlight a cell via bold font weight?

### ISSUE THREAD

**Issue by Jinjiang** [larswaechter/voici.js#19]
Hi, @larswaechter really nice job, BTW!

According to the highlighting feature in docs: https://lars-waechter.gitbook.io/voici.js/examples/highlighting

Is that possible if I can choose not only a different color but also a bold weight or italic font style, etc? Would be great if it could.

Thanks.

**Comment by larswaechter** [comment]
Hi @Jinjiang ,

thanks for your feedback! I added bold, italic and underline options in PR #21. Will be included in the next release.
